#! /bin/sh


sxhkd &

if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then
  xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 1920x1080 --rotate normal --right-of eDP-1
fi

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -model pc104 -layout us,ara -option grp:alt_shift_toggle &


bspc monitor -d 1 2 3 4 5 6 7 8 9


bspc config border_width         2
bspc config window_gap          8
bspc config top_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
obspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"


feh --bg-scale Downloads/wa.jpg
picom --config $HOME/.config/picom/picom.conf &
polybar &
dunst &
